package me.kitakeyos.j2me.infrastructure.hook;

import me.kitakeyos.j2me.domain.hook.model.HookInvocation;
import me.kitakeyos.j2me.domain.hook.model.MethodInterceptor;
import me.kitakeyos.j2me.domain.hook.model.MethodSignature;
import me.kitakeyos.j2me.domain.hook.repository.HookLookup;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Runtime end of the hook mechanism: every rewritten method calls
 * {@link #dispatch} instead of running its own body.
 *
 * <p>Everything here is {@code public static} because it is called straight
 * from generated bytecode. Like {@code PaintThrottleConfig}, this class lives
 * on the launcher classpath — {@code EmulatorClassLoader} delegates non-MIDlet
 * classes to its parent, so the rewritten MIDlet code resolves it with no
 * cross-loader tricks.
 *
 * <p>The generated call is:
 * <pre>
 * dispatch(instanceId, "com/game/Canvas", "keyPressed", "(I)V", this, new Object[]{ Integer.valueOf(p0) })
 * </pre>
 * and the {@code toXxx} helpers turn the {@code Object} result back into the
 * method's declared return type — which also keeps the generated bytecode free
 * of casts and null checks.
 */
public final class HookDispatcher {

    private static final Logger logger = Logger.getLogger(HookDispatcher.class.getName());

    /** Descriptor of {@link #dispatch}, used when emitting the call. */
    public static final String DISPATCH_DESCRIPTOR =
            "(ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;[Ljava/lang/Object;)"
                    + "Ljava/lang/Object;";

    private static final OriginalMethodResolver RESOLVER = new OriginalMethodResolver();

    private static volatile HookLookup lookup = InMemoryHookRegistry.getInstance();

    private HookDispatcher() {
    }

    /**
     * Point the dispatcher at a different hook store. Exists for tests; the
     * default is the shared {@link InMemoryHookRegistry}.
     */
    public static void setLookup(HookLookup hookLookup) {
        lookup = hookLookup == null ? InMemoryHookRegistry.getInstance() : hookLookup;
    }

    /**
     * Register the loader that owns an instance's classes.
     * Called by {@code EmulatorClassLoader} on construction.
     */
    public static void bindClassLoader(int instanceId, ClassLoader classLoader) {
        RESOLVER.bindClassLoader(instanceId, classLoader);
    }

    /**
     * Drop cached reflection state for a stopped instance, so its classloader
     * can be collected.
     */
    public static void release(int instanceId) {
        RESOLVER.release(instanceId);
    }

    /**
     * Entry point called by every rewritten method.
     *
     * @param instanceId emulator instance the rewritten class belongs to
     * @param owner      declaring class in internal form
     * @param name       original method name
     * @param descriptor original method descriptor
     * @param target     receiver, or {@code null} for a static method
     * @param arguments  boxed arguments in declaration order
     * @return value the original caller receives
     * @throws Throwable whatever the interceptor or the original body throws
     */
    public static Object dispatch(int instanceId, String owner, String name, String descriptor,
            Object target, Object[] arguments) throws Throwable {

        MethodSignature signature = MethodSignature.of(owner, name, descriptor);
        HookInvocation invocation = new ReflectiveHookInvocation(instanceId, signature, target, arguments, RESOLVER);

        MethodInterceptor interceptor = lookup.find(instanceId, signature);
        if (interceptor == null) {
            // Unregistered after the class was loaded — behave exactly like the original.
            return invocation.proceed();
        }

        try {
            return interceptor.intercept(invocation);
        } catch (Throwable t) {
            logger.log(Level.WARNING, "Hook " + signature + " (instance #" + instanceId + ") threw", t);
            throw t;
        }
    }

    // --- Return value coercion, called from generated bytecode ---------------
    // Lenient on purpose: a hook returning Integer for a long-returning method
    // is a convenience, not a bug. null always means "the type's default".

    public static boolean toBoolean(Object value) {
        return value instanceof Boolean && (Boolean) value;
    }

    public static byte toByte(Object value) {
        return value instanceof Number ? ((Number) value).byteValue() : 0;
    }

    public static char toChar(Object value) {
        if (value instanceof Character) {
            return (Character) value;
        }
        return value instanceof Number ? (char) ((Number) value).intValue() : 0;
    }

    public static short toShort(Object value) {
        return value instanceof Number ? ((Number) value).shortValue() : 0;
    }

    public static int toInt(Object value) {
        if (value instanceof Number) {
            return ((Number) value).intValue();
        }
        return value instanceof Character ? (Character) value : 0;
    }

    public static long toLong(Object value) {
        if (value instanceof Number) {
            return ((Number) value).longValue();
        }
        return value instanceof Character ? (Character) value : 0L;
    }

    public static float toFloat(Object value) {
        return value instanceof Number ? ((Number) value).floatValue() : 0f;
    }

    public static double toDouble(Object value) {
        return value instanceof Number ? ((Number) value).doubleValue() : 0d;
    }
}
